name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-27"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGFhYTdjMWQtYWZmMC00ZGM2LTk5ZmUtYTBlMWIwZjkzZjg1IiwidGVuYW50X2lkIjoiZjFmNjAyNGNkZGU4ZGE3NTBlMTRjZDkyZGM2ZGE1MjUxZjcxOTUwZDBlNjRkOWY0YzAyMGZhZGM4OTk5OTFkZiIsImludGVybmFsX3NlY3JldCI6IjQ0ZDc0OThmLTE0YTctNDcxOS1iOTM5LTVkZWJiMDVmMjE1NyJ9.fwKG42fqxFe6AJlc01HsdT1SbYnJayduf9csyxzG8xc"
JWT_SECRET="shivnandan"